# application.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/newsdb
    username: islam
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: 1111

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  check-client-api-header: true
  client-api-key: 12345
  check-user-id-header: true

security:
    jwt:
      token-prefix: "Bearer"
      header: "Authorization"
      access:
        secret: "access-secret-key-example"
        expiration: 15m
      refresh:
        secret: "refresh-secret-key-example"
        expiration: 7d


