# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: newsapp_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: islam
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: newsdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
